In [1]:
import pandas as pd
import numpy as np

In [2]:
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import OneHotEncoder
from sklearn.preprocessing import OrdinalEncoder

In [3]:
df = pd.read_csv(r"C:\Users\kadit\ML-Journey\datasets\covid_toy.csv")

In [4]:
df.head()

   age  gender  fever cough     city has_covid
0   60    Male  103.0  Mild  Kolkata        No
1   27    Male  100.0  Mild    Delhi       Yes
2   42    Male  101.0  Mild    Delhi        No
3   31  Female   98.0  Mild  Kolkata        No
4   65  Female  101.0  Mild   Mumbai        No

In [5]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(df.drop(columns=['has_covid']), df['has_covid'], test_size=0.2)

In [6]:
X_train.head()

    age  gender  fever   cough       city
10   75  Female    NaN    Mild      Delhi
30   15    Male  101.0    Mild      Delhi
74   34  Female  104.0  Strong      Delhi
79   48  Female  103.0    Mild    Kolkata
67   65    Male   99.0    Mild  Bangalore

1. Without Column Transformer:

In [11]:
# Adding simpleimputer to 'fever'col.

si = SimpleImputer ()
X_train_fever = si.fit_transform(X_train[['fever']])

# Also the test data

X_test_fever = si.transform(X_test[['fever']])

X_train_fever.shape, X_test_fever.shape

((80, 1), (20, 1))

In [ ]:
# OE -> 'cough' col.

oe = OrdinalEncoder(categories=[['Mild', 'Strong']])
X_train_cough = oe.fit_transform(X_train[['cough']])

# Also the test data

X_test_cough = oe.transform(X_test[['cough']])

X_train_cough.shape, X_test_cough.shape

((80, 1), (20, 1))

In [23]:
# OHE on 'gender' and 'city' col.

ohe = OneHotEncoder(drop ='first')
X_train_gender_city = ohe.fit_transform(X_train[['gender', 'city']])

# Also the test data

X_test_gender_city = ohe.transform(X_test[['gender', 'city']])

X_train_gender_city.shape

(80, 4)

In [24]:
# Extracting 'age' col. 

X_train_age = X_train.drop (columns=['gender', 'city', 'fever', 'cough']).values

# Also the test data

X_test_age = X_test.drop (columns=['gender', 'city', 'fever', 'cough']).values

X_train_age.shape, X_test_age.shape

((80, 1), (20, 1))

In [26]:
# Concatenating all the transformed features into a single array for training and testing:

X_train_transformed = np.concatenate([X_train_fever, X_train_cough, X_train_gender_city.toarray(), X_train_age], axis=1)

X_test_transformed = np.concatenate([X_test_fever, X_test_cough, X_test_gender_city.toarray(), X_test_age], axis=1)

X_train_transformed.shape, X_test_transformed.shape

((80, 7), (20, 7))

2. With Column Transform:

In [28]:
from sklearn.compose import ColumnTransformer

In [29]:
transformer = ColumnTransformer(transformers = [
    ('tnf1', SimpleImputer (), ['fever']),
    ('tnf2', OrdinalEncoder(categories=[['Mild', 'Strong']]), ['cough']),
    ('tnf3', OneHotEncoder(drop ='first'), ['gender', 'city'])
    ], remainder = 'passthrough')

In [41]:
X_train_transformed = transformer.fit_transform(X_train)
X_test_transformed = transformer.transform(X_test)

In [44]:
X_train_transformed.shape

(80, 7)